-- Run this file in Supabase SQL Editor.
-- It creates the analytics tables/views used by AdminPage.

create table if not exists public.cart_events (
  id bigint generated by default as identity primary key,
  user_id uuid null,
  product_id text null,
  variant_id text null,
  event_type text not null check (event_type in ('add', 'remove', 'update', 'checkout', 'clear')),
  quantity integer not null default 0,
  previous_quantity integer not null default 0,
  session_id text null,
  created_at timestamptz not null default now()
);

create index if not exists idx_cart_events_created_at on public.cart_events (created_at desc);
create index if not exists idx_cart_events_product_id on public.cart_events (product_id);
create index if not exists idx_cart_events_user_id on public.cart_events (user_id);

alter table public.order_items
  add column if not exists product_name text,
  add column if not exists product_category text,
  add column if not exists product_image_url text;

create or replace view public.product_variants as
select
  p.id::text as variant_id,
  p.id as product_id,
  p.name,
  p.category,
  coalesce(p.stock, 0) as stock
from public.products p;

create or replace view public.most_added_to_cart as
select
  p.name,
  p.category,
  count(*)::bigint as times_added,
  coalesce(sum(ce.quantity), 0)::bigint as total_quantity_added
from public.cart_events ce
left join public.products p on p.id::text = ce.product_id
where ce.event_type = 'add'
group by p.name, p.category
order by times_added desc, total_quantity_added desc;

create or replace view public.cart_analytics as
select
  date_trunc('day', ce.created_at)::date as date,
  count(distinct ce.user_id)::bigint as users_with_cart,
  count(*)::bigint as total_cart_items,
  coalesce(avg(nullif(ce.quantity, 0)), 0)::numeric(10,2) as avg_quantity_per_item
from public.cart_events ce
group by date_trunc('day', ce.created_at)::date
order by date desc;

create or replace view public.popular_products as
select
  coalesce(p.name, oi.product_name) as name,
  coalesce(p.category, oi.product_category) as category,
  count(distinct oi.order_id)::bigint as times_ordered,
  coalesce(sum(oi.quantity), 0)::bigint as total_quantity_sold,
  coalesce(sum(oi.quantity * oi.price), 0)::numeric(12,2) as total_revenue
from public.order_items oi
left join public.products p on p.id = oi.product_id
group by coalesce(p.name, oi.product_name), coalesce(p.category, oi.product_category)
order by times_ordered desc, total_quantity_sold desc;

create or replace view public.daily_sales as
select
  date_trunc('day', o.created_at)::date as date,
  count(*)::bigint as total_orders,
  coalesce(sum(o.total), 0)::numeric(12,2) as total_revenue,
  coalesce(avg(o.total), 0)::numeric(12,2) as average_order_value,
  count(distinct o.user_id)::bigint as unique_customers
from public.orders o
group by date_trunc('day', o.created_at)::date
order by date desc;
